#!/usr/bin/env python3.7

import random
import json
import os


files=int(os.getenv('fileCount') or 100)

words=[word.strip() for word in open('/usr/share/dict/words').readlines()]

for no in range(files):
    amount=random.uniform(1,1000)
    content={ 'receipt':random.choice(words),
              'bill':'%.2f' % amount
            }
    with open(f'./json_files/bill_{no}.json','w') as f:
        json.dump(content, f)

