#!/usr/bin/env python3.7
print('hello, Deepak')
print('time to complete Python')
print('time to complete Python')
print('time to complete Python')
"""
print('time to complete Python')
print('time to complete Python')
print('time to complete Python')
print('time to complete Python')
print('time to complete Python')
print('time to complete Python')
"""
