#!/usr/bin/env python3.7

import os
import json
import random


total_bill=0

for i in range(100):
    with open(f'./bill/bill_{i}.json', 'r') as f:
        d=json.loads(f.read())
        b= float(d.get('bill'))
        total_bill+=b

print('The total bill is:' "%.2f" % total_bill)
